### ISSUE TITLE
val.json 데이터에 대한 nDCG 계산(에러)

### ISSUE THREAD

**Issue by gaeul-3041** [LimTurtle/GA_Saronite#74]
- 노래 추천 모형에서의 문제점
  - 샘플링된 데이터로 만들어진 vocabulary로는 validation 데이터에서 처음 보는 태그를 읽으면 에러 발생
  - 학습 데이터를 최대한 원본 그대로 쓰는 게 불가피한데, 그러기엔 메모리 에러가 아직 해결책이 마땅히 없음

**Comment by LimTurtle** [comment]
현재 모형 구조 생각해보면 사용자 플레이리스트 내 존재하는 모든 태그, 장르를 뽑아낸 뒤에 추천이 이뤄지고 있어서, 이 부분에 validation 데이터를 넣으면 해결될 것 같음
